swiftmailer:
    default_mailer: default
    mailers:
        default:
            url:                  '%env(MAILER_URL)%'
            spool:
                type:             file
                path:             '%kernel.cache_dir%/swiftmailer/spool'
                # Used by "service" type
                id:               null
            delivery_addresses:   []
            transport:            sendmail
            command:              '/usr/sbin/sendmail -bs'
            local_domain:         guochenglong.com
            sender_address:       'chenglong.guo@foxmail.com'
            logging:              true
            delivery_whitelist:   []

