swiftmailer:
    default_mailer: default
    mailers:
        default:
            url:                  '%env(MAILER_URL)%'
            spool:
                type:             file
                path:             '%kernel.cache_dir%/swiftmailer/spool'
                # Used by "service" type
                id:               null
            delivery_addresses:   []
            transport:            smtp
            command:              '/usr/sbin/sendmail -bs'
            timeout:              30
            local_domain:         guochenglong.com
            encryption:           null
            username:             null
            password:             null
            host:                 localhost
            port:                 null
            source_ip:            50.116.9.143
            stream_options:       []
            auth_mode:            null
            sender_address:       ~
            logging:              true
            delivery_whitelist:   []

