swiftmailer:
    default_mailer: default
    mailers:
        default:
            url:                  '%env(MAILER_URL)%'
            sender_address:       'chenglong.guo@foxmail.com'
            timeout:              10
            stream_options:
                ssl:
                    verify_peer:      false
                    verify_peer_name: false

