swiftmailer:
    default_mailer: default
    mailers:
        default:
            delivery_addresses:   []
            transport:            sendmail
            command:              '/usr/sbin/sendmail -bs'
            local_domain:         guochenglong.com
            sender_address:       'chenglong.guo@foxmail.com'
            logging:              true
            delivery_whitelist:   []

